---
apiVersion: v1
kind: Service
metadata:
  name: catch
  labels:
    app: catch
spec:
  ports:
    - name: catch
      port: 8080
      targetPort: 8000
      protocol: TCP
  selector:
    app: catch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catch
  labels:
    app: catch
spec:
  selector:
    matchLabels:
      app: catch
  template:
    metadata:
      labels:
        app: catch
    spec:
      containers:
        - name: catch
          image: "codingric/catch-test:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            # an http probe
            httpGet:
              path: /go
              port: 8000
            initialDelaySeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            # an http probe
            httpGet:
              path: /go
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catch
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: catch.salinas.id.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: catch
                port:
                  number: 8080
