kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-development
  label:
    version: v1
spec:
  selector:
    matchLabels:
      app: test-development
  template:
    metadata:
      labels:
        app: test-development
        version: v1
    spec:
      containers:
        - name: test-development
          image: IMG
          ports:
            - containerPort: 8000
              name: http
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
            requests:
              cpu: 0.1
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          envFrom:
            - secretRef:
                name: test-secrets
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-development
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
