# Build the manager binary
FROM gcr.io/cloud-builders/go as builder

WORKDIR /app
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o golang-test main.go

# Use distroless as minimal base image to package binary
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /app/golang-test .
EXPOSE 8000

ENTRYPOINT ["/golang-test"]